# -*- coding: utf-8 -*-
"""Udyam-Sarthi: MSME Compliance Navigator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1915vVsscynZM348ymrliBYHif3xVy_cL
"""

"""
Udyam-Sarthi - MSME Compliance Navigator
Run this in Google Colab to deploy with Gradio
"""

# Installation (run in Colab first cell)
# !pip install gradio anthropic python-dateutil

import gradio as gr
from datetime import datetime, timedelta
from dateutil.relativedelta import relativedelta
import json
import calendar

# Business profiles database
BUSINESS_PROFILES = {
    "screen_printing": {
        "name": "Screen Printing Unit",
        "typical_compliances": ["GST", "Factory License", "Pollution Control", "ESI", "PF", "Labour License"],
        "risk_areas": ["pollution_norms", "labor_compliance", "gst_filing"]
    },
    "textile": {
        "name": "Textile Manufacturing",
        "typical_compliances": ["GST", "Factory License", "Pollution Control", "ESI", "PF", "Trade License"],
        "risk_areas": ["pollution_norms", "export_compliance", "labor_compliance"]
    },
    "food_processing": {
        "name": "Food Processing Unit",
        "typical_compliances": ["GST", "FSSAI License", "Factory License", "ESI", "PF", "Trade License"],
        "risk_areas": ["food_safety", "gst_filing", "labor_compliance"]
    },
    "manufacturing": {
        "name": "General Manufacturing",
        "typical_compliances": ["GST", "Factory License", "ESI", "PF", "Trade License"],
        "risk_areas": ["gst_filing", "labor_compliance", "factory_safety"]
    }
}

# Compliance calendar generator
def generate_compliance_calendar(business_type, turnover, employees, state, current_date):
    """Generate personalized compliance calendar"""

    turnover_lakhs = float(turnover)
    num_employees = int(employees)

    calendar_items = []

    # GST Compliance
    if turnover_lakhs > 40:  # Above GST threshold
        # Monthly GSTR-3B
        for i in range(12):
            due_date = current_date + relativedelta(months=i+1)
            due_date = due_date.replace(day=20)
            calendar_items.append({
                "date": due_date.strftime("%Y-%m-%d"),
                "compliance": "GSTR-3B Filing",
                "description": f"Monthly GST return for {due_date.strftime('%B %Y')}",
                "priority": "High",
                "language": "en"
            })

        # Quarterly GSTR-1
        for quarter in range(1, 5):
            due_date = current_date + relativedelta(months=quarter*3)
            due_date = due_date.replace(day=13)
            calendar_items.append({
                "date": due_date.strftime("%Y-%m-%d"),
                "compliance": "GSTR-1 Filing",
                "description": f"Quarterly GST return - Q{quarter}",
                "priority": "High",
                "language": "en"
            })

    # PF/ESI Compliance (if employees > 10 for ESI, > 20 for PF)
    if num_employees >= 10:
        for i in range(12):
            due_date = current_date + relativedelta(months=i+1)
            due_date = due_date.replace(day=15)
            calendar_items.append({
                "date": due_date.strftime("%Y-%m-%d"),
                "compliance": "ESI Payment",
                "description": f"ESI contribution for {due_date.strftime('%B %Y')}",
                "priority": "High",
                "language": "en"
            })

    if num_employees >= 20:
        for i in range(12):
            due_date = current_date + relativedelta(months=i+1)
            due_date = due_date.replace(day=15)
            calendar_items.append({
                "date": due_date.strftime("%Y-%m-%d"),
                "compliance": "PF Payment",
                "description": f"PF contribution for {due_date.strftime('%B %Y')}",
                "priority": "High",
                "language": "en"
            })

    # Factory License Renewal (Annual)
    license_renewal = current_date + relativedelta(months=6)
    calendar_items.append({
        "date": license_renewal.strftime("%Y-%m-%d"),
        "compliance": "Factory License Renewal",
        "description": "Annual factory license renewal",
        "priority": "Medium",
        "language": "en"
    })

    # Pollution Control (for manufacturing units)
    if business_type in ["screen_printing", "textile", "manufacturing"]:
        pollution_check = current_date + relativedelta(months=4)
        calendar_items.append({
            "date": pollution_check.strftime("%Y-%m-%d"),
            "compliance": "Pollution Control Audit",
            "description": f"Six-monthly pollution compliance for {state}",
            "priority": "High",
            "language": "en"
        })

    # Sort by date
    calendar_items.sort(key=lambda x: x['date'])

    return calendar_items

# Regulatory change alerts
def get_regulatory_alerts(business_type, state, language="en"):
    """Simulate regulatory change detection"""

    alerts = []

    # Sample alerts based on business type and state
    if business_type == "screen_printing" and state == "Gujarat":
        alerts.append({
            "title": "New Gujarat Pollution Norms for Textile Units" if language == "en"
                     else "ટેક્સટાઇલ એકમો માટે નવા ગુજરાત પ્રદૂષણ ધોરણો",
            "description": "Gujarat Pollution Control Board has issued new emission standards effective from next quarter" if language == "en"
                          else "ગુજરાત પ્રદૂષણ નિયંત્રણ બોર્ડે આગામી ક્વાર્ટરથી અમલમાં આવતા નવા ઉત્સર્જન ધોરણો જારી કર્યા છે",
            "effective_date": (datetime.now() + timedelta(days=90)).strftime("%Y-%m-%d"),
            "action_required": "Update pollution control equipment and get new compliance certificate" if language == "en"
                              else "પ્રદૂષણ નિયંત્રણ સાધનો અપડેટ કરો અને નવું પાલન પ્રમાણપત્ર મેળવો",
            "priority": "High"
        })

    if state == "Gujarat":
        alerts.append({
            "title": "GST Rate Changes for Printed Materials" if language == "en"
                     else "પ્રિન્ટેડ સામગ્રી માટે જીએસટી દર ફેરફાર",
            "description": "New GST rates applicable from next month for printed packaging materials" if language == "en"
                          else "આગામી મહિનાથી પ્રિન્ટેડ પેકેજિંગ સામગ્રી માટે નવા જીએસટી દરો લાગુ",
            "effective_date": (datetime.now() + timedelta(days=30)).strftime("%Y-%m-%d"),
            "action_required": "Update billing software with new GST rates" if language == "en"
                              else "નવા જીએસટી દરો સાથે બિલિંગ સોફ્ટવેર અપડેટ કરો",
            "priority": "Medium"
        })

    alerts.append({
        "title": "Annual ITR Filing Deadline Approaching" if language == "en"
                 else "વાર્ષિક આઈટીઆર ફાઇલિંગ અંતિમ તારીખ નજીક આવી રહી છે",
        "description": "Last date for filing Income Tax Returns for FY 2023-24" if language == "en"
                      else "નાણાકીય વર્ષ 2023-24 માટે આવકવેરા રિટર્ન ફાઇલ કરવાની છેલ્લી તારીખ",
        "effective_date": "2024-07-31",
        "action_required": "Prepare and file ITR before deadline" if language == "en"
                          else "અંતિમ તારીખ પહેલાં આઈટીઆર તૈયાર કરો અને ફાઇલ કરો",
        "priority": "High"
    })

    return alerts

# Cost savings calculator
def calculate_savings(turnover, employees):
    """Calculate estimated annual savings"""

    turnover_lakhs = float(turnover)
    num_employees = int(employees)

    # Base CA cost
    base_ca_cost = 50000 * 12  # ₹50k monthly

    # Platform cost (subscription model)
    platform_cost = 30000  # Annual subscription

    # Savings breakdown
    savings = {
        "current_ca_cost": base_ca_cost,
        "platform_cost": platform_cost,
        "net_savings": base_ca_cost - platform_cost,
        "time_saved_hours": 500,  # Hours saved annually
        "penalty_avoidance": 50000  # Estimated penalty avoidance
    }

    return savings

# Document auto-fill simulator
def generate_prefilled_form(business_name, gstin, turnover, employees, previous_data=None):
    """Generate pre-filled form data"""

    form_data = {
        "business_name": business_name,
        "gstin": gstin,
        "turnover": turnover,
        "employees": employees,
        "filing_date": datetime.now().strftime("%Y-%m-%d"),
        "financial_year": "2024-25"
    }

    # Simulate pulling from previous filings
    if previous_data:
        form_data.update({
            "bank_account": "XXXX1234",
            "authorized_signatory": "Previous filing data loaded",
            "address": "As per previous return"
        })

    return json.dumps(form_data, indent=2)

# Main Gradio Interface
def create_compliance_dashboard():

    def process_business_setup(business_type, business_name, gstin, turnover, employees, state, language):
        """Process initial business setup and generate dashboard"""

        current_date = datetime.now()

        # Generate compliance calendar
        calendar = generate_compliance_calendar(business_type, turnover, employees, state, current_date)

        # Format calendar for display
        calendar_text = "📅 UPCOMING COMPLIANCE CALENDAR\n" + "="*50 + "\n\n"
        for item in calendar[:10]:  # Show next 10 items
            calendar_text += f"📌 {item['date']}\n"
            calendar_text += f"   {item['compliance']}\n"
            calendar_text += f"   {item['description']}\n"
            calendar_text += f"   Priority: {item['priority']}\n\n"

        # Get regulatory alerts
        alerts = get_regulatory_alerts(business_type, state, language)
        alerts_text = "🚨 REGULATORY ALERTS\n" + "="*50 + "\n\n"
        for alert in alerts:
            alerts_text += f"⚠️ {alert['title']}\n"
            alerts_text += f"   {alert['description']}\n"
            alerts_text += f"   Effective: {alert['effective_date']}\n"
            alerts_text += f"   Action: {alert['action_required']}\n"
            alerts_text += f"   Priority: {alert['priority']}\n\n"

        # Calculate savings
        savings = calculate_savings(turnover, employees)
        savings_text = "💰 COST SAVINGS ANALYSIS\n" + "="*50 + "\n\n"
        savings_text += f"Current CA Cost (Annual): ₹{savings['current_ca_cost']:,}\n"
        savings_text += f"Udyam-Sarthi Cost (Annual): ₹{savings['platform_cost']:,}\n"
        savings_text += f"NET SAVINGS: ₹{savings['net_savings']:,}\n\n"
        savings_text += f"Additional Benefits:\n"
        savings_text += f"• Time Saved: {savings['time_saved_hours']} hours/year\n"
        savings_text += f"• Penalty Avoidance: ₹{savings['penalty_avoidance']:,}\n"

        # Generate pre-filled form sample
        form_sample = generate_prefilled_form(business_name, gstin, turnover, employees, True)
        form_text = "📝 SAMPLE AUTO-FILLED FORM\n" + "="*50 + "\n\n"
        form_text += form_sample

        return calendar_text, alerts_text, savings_text, form_text

    # Create Gradio Interface
    with gr.Blocks(title="Udyam-Sarthi - MSME Compliance Navigator", theme=gr.themes.Soft()) as demo:

        gr.Markdown("""
        # 🏢 Udyam-Sarthi - MSME Compliance Navigator
        ### Your AI-Powered Compliance Assistant

        **Never miss a deadline. Never pay unnecessary penalties. Save ₹3-5 lakhs annually.**
        """)

        with gr.Row():
            with gr.Column(scale=1):
                gr.Markdown("## 📋 Business Profile Setup")

                business_type = gr.Dropdown(
                    choices=list(BUSINESS_PROFILES.keys()),
                    label="Business Type",
                    value="screen_printing"
                )

                business_name = gr.Textbox(
                    label="Business Name",
                    placeholder="e.g., Surat Print Solutions"
                )

                gstin = gr.Textbox(
                    label="GSTIN",
                    placeholder="24XXXXX1234X1ZX"
                )

                turnover = gr.Number(
                    label="Annual Turnover (in Lakhs)",
                    value=85
                )

                employees = gr.Number(
                    label="Number of Employees",
                    value=8
                )

                state = gr.Dropdown(
                    choices=["Gujarat", "Maharashtra", "Karnataka", "Tamil Nadu", "Delhi"],
                    label="State",
                    value="Gujarat"
                )

                language = gr.Radio(
                    choices=["en", "gu"],
                    label="Preferred Language",
                    value="en"
                )

                submit_btn = gr.Button("Generate Compliance Dashboard", variant="primary")

        with gr.Row():
            with gr.Column():
                gr.Markdown("## 📅 Compliance Calendar")
                calendar_output = gr.Textbox(
                    label="Upcoming Deadlines",
                    lines=15,
                    max_lines=20
                )

            with gr.Column():
                gr.Markdown("## 🚨 Regulatory Alerts")
                alerts_output = gr.Textbox(
                    label="Recent Changes & Updates",
                    lines=15,
                    max_lines=20
                )

        with gr.Row():
            with gr.Column():
                gr.Markdown("## 💰 Cost Savings")
                savings_output = gr.Textbox(
                    label="Annual Savings Analysis",
                    lines=10
                )

            with gr.Column():
                gr.Markdown("## 📝 Auto-Fill Preview")
                form_output = gr.Textbox(
                    label="Sample Pre-filled Form",
                    lines=10
                )

        submit_btn.click(
            fn=process_business_setup,
            inputs=[business_type, business_name, gstin, turnover, employees, state, language],
            outputs=[calendar_output, alerts_output, savings_output, form_output]
        )

        gr.Markdown("""
        ---
        ### 🎯 Key Features:
        - **Smart Calendar**: Automatic deadline tracking for GST, PF, ESI, licenses
        - **Change Detection**: Real-time alerts for new regulations in your industry
        - **Auto-Fill**: Pre-populate forms using previous filings
        - **Multi-language**: Support for regional languages
        - **Cost Savings**: Save ₹3-5 lakhs annually on compliance costs

        ### 💡 Perfect For:
        - Screen printing units
        - Textile manufacturers
        - Food processing units
        - General manufacturing MSMEs
        """)

    return demo

# Launch the application
if __name__ == "__main__":
    demo = create_compliance_dashboard()
    demo.launch(share=True)  # share=True creates public link in Colab